name: 'Create GitHub API Deployment'
brand:
  icon: 'download-cloud'
  color: 'orange'
description: 'Create a Deployment via the GitHub API'
inputs:
  token:
    description: 'This should be a token with access to your repository scoped in as a secret'
    required: true
  ref:
    description: The ref to deploy. This can be a branch, tag, or SHA.
      Defaults to the value of ${GITHUB_GITHUB_REPOSITORY}
    required: false
  task:
    description: 'Specifies a task to execute (e.g., deploy or deploy:migrations)'
    required: false
  payload:
    description: 'JSON payload with extra information about the deployment'
    required: false
  environment:
    description: 'Name for the target deployment environment (e.g., production, staging, qa)'
    required: false
  description:
    description: 'Short description of the deployment'
    required: false
outputs:
  id:
    description: 'The ID of the Deployment'
runs:
  using: 'node12'
  main: 'dist/index.js'
