name: 'test-local'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate VERSION
        run: echo "::set-env name=VERSION::$(git describe --tags --always --dirty)"
      - run: npm ci
      # - run: npm test
      - name: Create Deployment
        id: deploy
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          payload: ${{ env.VERSION }}
      - name: Get the deplopyment ID
        run: echo "The deployment ID was ${{ steps.deploy.outputs.id }}"
